/* ===== Офлайн-банк: работает без API-ключа ===== */
const BANK = {
  // адаптивный пул вопросов, level 1..6, со skill-тегом
  questions: [
    {level:1,skill:"Tenses",q:"She ___ to school every day.",options:["go","goes","going","gone"],answer:1,explain:"Present Simple, 3rd person singular → +s: goes."},
    {level:1,skill:"Prepositions",q:"I'm good ___ playing chess.",options:["in","at","on","for"],answer:1,explain:"good AT (doing) something — fixed collocation."},
    {level:1,skill:"Vocabulary",q:"Choose the synonym of 'big':",options:["tiny","large","narrow","weak"],answer:1,explain:"big = large."},
    {level:2,skill:"Tenses",q:"By the time we arrived, the film ___.",options:["started","has started","had started","starts"],answer:2,explain:"Past Perfect: an action before another past action — had started."},
    {level:2,skill:"Use of English",q:"He suggested ___ a break.",options:["to take","taking","take","took"],answer:1,explain:"suggest + V-ing → suggested taking."},
    {level:2,skill:"Grammar",q:"If I ___ you, I'd apologize.",options:["am","was","were","be"],answer:2,explain:"Second conditional: 'were' for all persons."},
    {level:3,skill:"Prepositions",q:"She apologized ___ being late.",options:["for","of","to","with"],answer:0,explain:"apologize FOR something."},
    {level:3,skill:"Vocabulary",q:"'To put off' means:",options:["to wear","to postpone","to remove","to start"],answer:1,explain:"put off = to postpone."},
    {level:3,skill:"Use of English",q:"Hardly ___ when it started to rain.",options:["we left","had we left","we had left","did we left"],answer:1,explain:"Inversion after 'Hardly': had we left."},
    {level:4,skill:"Grammar",q:"I'd rather you ___ smoke here.",options:["don't","didn't","not","wouldn't"],answer:1,explain:"I'd rather + past simple (didn't) when asking someone else to do/not do something."},
    {level:4,skill:"Tenses",q:"This time next week I ___ on a beach.",options:["will lie","will be lying","lie","am lying"],answer:1,explain:"Future Continuous: an action in progress at a specific future moment."},
    {level:4,skill:"Vocabulary",q:"A 'breakthrough' is:",options:["a failure","a major discovery","a short break","an argument"],answer:1,explain:"breakthrough = a major discovery or achievement."},
    {level:5,skill:"Use of English",q:"No sooner had he sat down ___ the phone rang.",options:["when","than","that","then"],answer:1,explain:"No sooner ... than (fixed structure)."},
    {level:5,skill:"Grammar",q:"___ his efforts, he failed.",options:["Despite","Although","However","Because"],answer:0,explain:"Despite + noun/gerund."},
    {level:5,skill:"Vocabulary",q:"'Meticulous' is closest to:",options:["careless","very careful","fast","lazy"],answer:1,explain:"meticulous = very careful and precise."},
  ],
  theory: {
    "Tenses":{title:"Tenses: key traps",html:"<h3>Perfect vs Simple</h3><p>Present Perfect links past to present: <code>I have lost my keys</code> (and I still don't have them). Past Simple is finished past with a time marker: <code>I lost them yesterday</code>.</p><h3>Past Perfect</h3><p>An action <b>before</b> another past action: <code>When I arrived, they had already left</code>.</p><ul><li><code>She has worked here since 2019</code> (still going)</li><li><code>By 2020 she had worked there for a year</code> (up to a past point)</li></ul>"},
    "Prepositions":{title:"Prepositions after verbs and adjectives",html:"<h3>Common pairings</h3><ul><li>good <code>at</code>, interested <code>in</code>, afraid <code>of</code></li><li>depend <code>on</code>, apologize <code>for</code>, succeed <code>in</code></li><li>responsible <code>for</code>, married <code>to</code>, similar <code>to</code></li></ul><p>Learn them as whole phrases — there's often no logic.</p>"},
    "Use of English":{title:"Use of English: inversion and gerunds",html:"<h3>Inversion</h3><p>After negative adverbs at the start, use inverted order: <code>Never have I seen...</code>, <code>Hardly had I left when...</code>, <code>No sooner had... than...</code>.</p><h3>Gerund / Infinitive</h3><ul><li>suggest, enjoy, avoid + <code>V-ing</code></li><li>decide, agree, manage + <code>to V</code></li></ul>"},
    "Grammar":{title:"B2 grammar: conditionals and wish",html:"<h3>Conditionals</h3><ul><li>2nd: <code>If I were rich, I would travel</code></li><li>3rd: <code>If I had known, I would have come</code></li></ul><h3>Wish</h3><p><code>I wish I knew</code> (I don't know now), <code>I wish I had known</code> (regret about the past).</p>"},
    "Vocabulary":{title:"B2+ vocabulary: phrasal verbs and idioms",html:"<h3>Phrasal verbs</h3><ul><li>put off = postpone</li><li>come up with = invent/think of</li><li>look into = investigate</li><li>carry out = perform/complete</li></ul><p>Learn them in a sentence context, not as a list.</p>"},
  },
  exercises: {
    _generic:[
      {type:"mc",q:"By next year I ___ here for a decade.",options:["work","will have worked","worked"],answer:1,explain:"Future Perfect."},
      {type:"fill",q:"She's interested ___ art.",answer:"in",alt:[],explain:"interested IN."},
      {type:"mc",q:"He avoided ___ the question.",options:["to answer","answering","answer"],answer:1,explain:"avoid + V-ing."},
      {type:"fill",q:"If I ___ (be) you, I'd rest.",answer:"were",alt:["was"],explain:"2nd conditional — were."},
      {type:"mc",q:"Never ___ such a view.",options:["I have seen","have I seen","I saw"],answer:1,explain:"Inversion after 'Never'."},
    ]
  }
};

/* ===== Тематические колоды слов (по темам и уровням) ===== */
/* поля карточки: w, ipa, pos, def, ex, syn */
const DECKS = [
 {id:"personality",name:"Personality & Character",icon:"🧠",lvl:"B2",words:[
  {w:"meticulous",ipa:"/məˈtɪkjələs/",pos:"adj",def:"very careful and precise about details",ex:"She's meticulous about her research.",syn:"thorough, scrupulous"},
  {w:"resilient",ipa:"/rɪˈzɪliənt/",pos:"adj",def:"able to recover quickly from difficulties",ex:"Kids are remarkably resilient.",syn:"tough, hardy"},
  {w:"pragmatic",ipa:"/præɡˈmætɪk/",pos:"adj",def:"dealing with things sensibly and realistically",ex:"Let's take a pragmatic approach.",syn:"practical, realistic"},
  {w:"candid",ipa:"/ˈkændɪd/",pos:"adj",def:"honest and straightforward",ex:"To be candid, I didn't like it.",syn:"frank, blunt"},
  {w:"diligent",ipa:"/ˈdɪlɪdʒənt/",pos:"adj",def:"hard-working and careful",ex:"A diligent student.",syn:"hard-working, conscientious"},
  {w:"arrogant",ipa:"/ˈærəɡənt/",pos:"adj",def:"having too high an opinion of yourself",ex:"Don't be so arrogant.",syn:"conceited, cocky"},
  {w:"genuine",ipa:"/ˈdʒenjuɪn/",pos:"adj",def:"real and sincere",ex:"A genuine smile.",syn:"authentic, sincere"},
  {w:"reckless",ipa:"/ˈrekləs/",pos:"adj",def:"acting without thinking of consequences",ex:"Reckless driving.",syn:"careless, rash"},
  {w:"keen",ipa:"/kiːn/",pos:"adj",def:"very enthusiastic about something",ex:"She's keen on tennis.",syn:"eager, enthusiastic"},
  {w:"reluctant",ipa:"/rɪˈlʌktənt/",pos:"adj",def:"unwilling and hesitant",ex:"He was reluctant to go.",syn:"unwilling, hesitant"},
  {w:"wary",ipa:"/ˈweəri/",pos:"adj",def:"cautious and watchful of danger",ex:"Be wary of scams.",syn:"cautious, careful"},
  {w:"earnest",ipa:"/ˈɜːnɪst/",pos:"adj",def:"serious and sincere",ex:"An earnest effort.",syn:"sincere, serious"},
  {w:"sceptical",ipa:"/ˈskeptɪkl/",pos:"adj",def:"doubtful, not easily convinced",ex:"I'm sceptical about it.",syn:"doubtful, dubious"},
  {w:"stubborn",ipa:"/ˈstʌbən/",pos:"adj",def:"refusing to change your mind",ex:"He's as stubborn as a mule.",syn:"obstinate, headstrong"},
  {w:"humble",ipa:"/ˈhʌmbl/",pos:"adj",def:"not proud; modest about yourself",ex:"She stayed humble after winning.",syn:"modest, unassuming"},
  {w:"witty",ipa:"/ˈwɪti/",pos:"adj",def:"clever and funny",ex:"A witty remark.",syn:"sharp, clever"},
 ]},
 {id:"describing",name:"Describing Things",icon:"🎨",lvl:"B2",words:[
  {w:"ubiquitous",ipa:"/juːˈbɪkwɪtəs/",pos:"adj",def:"present everywhere at once",ex:"Smartphones are now ubiquitous.",syn:"omnipresent, everywhere"},
  {w:"ambiguous",ipa:"/æmˈbɪɡjuəs/",pos:"adj",def:"open to more than one interpretation",ex:"His answer was deliberately ambiguous.",syn:"vague, unclear"},
  {w:"tedious",ipa:"/ˈtiːdiəs/",pos:"adj",def:"too long, slow and boring",ex:"Filling forms is tedious.",syn:"boring, dull"},
  {w:"versatile",ipa:"/ˈvɜːsətaɪl/",pos:"adj",def:"able to adapt to many functions",ex:"He's a versatile player.",syn:"adaptable, flexible"},
  {w:"notorious",ipa:"/nəʊˈtɔːriəs/",pos:"adj",def:"famous for something bad",ex:"The area is notorious for crime.",syn:"infamous"},
  {w:"profound",ipa:"/prəˈfaʊnd/",pos:"adj",def:"very great or deep",ex:"It had a profound effect on me.",syn:"deep, intense"},
  {w:"blatant",ipa:"/ˈbleɪtnt/",pos:"adj",def:"done openly and unashamedly (of bad things)",ex:"That's a blatant lie.",syn:"obvious, flagrant"},
  {w:"mundane",ipa:"/mʌnˈdeɪn/",pos:"adj",def:"ordinary and dull",ex:"I'm tired of mundane tasks.",syn:"ordinary, banal"},
  {w:"compelling",ipa:"/kəmˈpelɪŋ/",pos:"adj",def:"so interesting it grabs your attention",ex:"A compelling argument.",syn:"convincing, gripping"},
  {w:"daunting",ipa:"/ˈdɔːntɪŋ/",pos:"adj",def:"seeming difficult and intimidating",ex:"A daunting challenge.",syn:"intimidating, scary"},
  {w:"intricate",ipa:"/ˈɪntrɪkət/",pos:"adj",def:"very detailed and complicated",ex:"An intricate design.",syn:"complex, elaborate"},
  {w:"vivid",ipa:"/ˈvɪvɪd/",pos:"adj",def:"producing strong, clear images",ex:"A vivid memory.",syn:"bright, striking"},
  {w:"subtle",ipa:"/ˈsʌtl/",pos:"adj",def:"delicate, not obvious",ex:"A subtle difference.",syn:"slight, delicate"},
  {w:"prominent",ipa:"/ˈprɒmɪnənt/",pos:"adj",def:"important and well-known",ex:"A prominent scientist.",syn:"leading, famous"},
  {w:"impeccable",ipa:"/ɪmˈpekəbl/",pos:"adj",def:"perfect, without faults",ex:"Impeccable manners.",syn:"flawless, perfect"},
  {w:"overwhelming",ipa:"/ˌəʊvəˈwelmɪŋ/",pos:"adj",def:"very great in amount or effect",ex:"Overwhelming support.",syn:"huge, immense"},
 ]},
 {id:"phrasal",name:"Phrasal Verbs",icon:"🔗",lvl:"B2",words:[
  {w:"come up with",ipa:"/kʌm ʌp wɪð/",pos:"phrase",def:"to think of an idea or plan",ex:"She came up with a plan.",syn:"devise, invent"},
  {w:"put off",ipa:"/pʊt ɒf/",pos:"phrase",def:"to postpone; or to discourage someone",ex:"Don't put it off.",syn:"postpone, delay"},
  {w:"look into",ipa:"/lʊk ˈɪntə/",pos:"phrase",def:"to investigate something",ex:"I'll look into it.",syn:"investigate, examine"},
  {w:"carry out",ipa:"/ˈkæri aʊt/",pos:"phrase",def:"to perform or complete a task",ex:"They carried out a study.",syn:"perform, conduct"},
  {w:"figure out",ipa:"/ˈfɪɡə aʊt/",pos:"phrase",def:"to understand or solve something",ex:"I figured out the answer.",syn:"work out, solve"},
  {w:"get the hang of",ipa:"/ɡet ðə hæŋ ɒv/",pos:"phrase",def:"to learn how to do something",ex:"You'll get the hang of it.",syn:"master, learn"},
  {w:"resort to",ipa:"/rɪˈzɔːt/",pos:"phrase",def:"to use something bad because nothing else works",ex:"Don't resort to lying.",syn:"fall back on"},
  {w:"cope with",ipa:"/kəʊp wɪð/",pos:"phrase",def:"to deal with a difficult situation",ex:"How do you cope with stress?",syn:"manage, handle"},
  {w:"stand out",ipa:"/stænd aʊt/",pos:"phrase",def:"to be clearly noticeable",ex:"Her work stands out.",syn:"be noticeable"},
  {w:"rule out",ipa:"/ruːl aʊt/",pos:"phrase",def:"to exclude as a possibility",ex:"We can't rule it out.",syn:"exclude, dismiss"},
  {w:"point out",ipa:"/pɔɪnt aʊt/",pos:"phrase",def:"to make someone aware of something",ex:"She pointed out the error.",syn:"indicate, note"},
  {w:"keep up with",ipa:"/kiːp ʌp wɪð/",pos:"phrase",def:"to stay at the same level/pace",ex:"Keep up with the news.",syn:"stay current"},
  {w:"put up with",ipa:"/pʊt ʌp wɪð/",pos:"phrase",def:"to tolerate something annoying",ex:"I won't put up with rudeness.",syn:"tolerate, endure"},
  {w:"bring about",ipa:"/brɪŋ əˈbaʊt/",pos:"phrase",def:"to cause something to happen",ex:"The law brought about change.",syn:"cause, trigger"},
  {w:"turn down",ipa:"/tɜːn daʊn/",pos:"phrase",def:"to refuse or reject",ex:"He turned down the offer.",syn:"reject, decline"},
  {w:"work out",ipa:"/wɜːk aʊt/",pos:"phrase",def:"to solve, or to exercise",ex:"It all worked out fine.",syn:"resolve, exercise"},
 ]},
 {id:"idioms",name:"Idioms & Expressions",icon:"💬",lvl:"B2",words:[
  {w:"a piece of cake",ipa:"/ə piːs ɒv keɪk/",pos:"idiom",def:"something very easy",ex:"The test was a piece of cake.",syn:"easy, effortless"},
  {w:"break the ice",ipa:"/breɪk ðə aɪs/",pos:"idiom",def:"to make people feel relaxed at first",ex:"A joke broke the ice.",syn:"ease tension"},
  {w:"hit the books",ipa:"/hɪt ðə bʊks/",pos:"idiom",def:"to study hard",ex:"Time to hit the books.",syn:"study, cram"},
  {w:"under the weather",ipa:"/ˈʌndə ðə ˈweðə/",pos:"idiom",def:"feeling slightly ill",ex:"I'm a bit under the weather.",syn:"sick, ill"},
  {w:"on the same page",ipa:"/ɒn ðə seɪm peɪdʒ/",pos:"idiom",def:"in agreement; sharing understanding",ex:"Are we on the same page?",syn:"in agreement"},
  {w:"cut corners",ipa:"/kʌt ˈkɔːnəz/",pos:"idiom",def:"to do something cheaply or badly to save effort",ex:"Don't cut corners on safety.",syn:"skimp"},
  {w:"bite the bullet",ipa:"/baɪt ðə ˈbʊlɪt/",pos:"idiom",def:"to face something unpleasant bravely",ex:"Just bite the bullet.",syn:"face it, endure"},
  {w:"the bottom line",ipa:"/ˈbɒtəm laɪn/",pos:"idiom",def:"the most important fact",ex:"The bottom line is we're broke.",syn:"the key point"},
  {w:"once in a blue moon",ipa:"/wʌns ɪn ə bluː muːn/",pos:"idiom",def:"very rarely",ex:"I see him once in a blue moon.",syn:"rarely, seldom"},
  {w:"the tip of the iceberg",ipa:"/ðə tɪp ɒv ðə ˈaɪsbɜːɡ/",pos:"idiom",def:"a small visible part of a much bigger problem",ex:"This is just the tip of the iceberg.",syn:"a small part"},
  {w:"call it a day",ipa:"/kɔːl ɪt ə deɪ/",pos:"idiom",def:"to stop working for the day",ex:"Let's call it a day.",syn:"finish, stop"},
  {w:"get cold feet",ipa:"/ɡet kəʊld fiːt/",pos:"idiom",def:"to suddenly become too nervous to do something",ex:"He got cold feet before the wedding.",syn:"lose nerve"},
  {w:"a blessing in disguise",ipa:"/ə ˈblesɪŋ ɪn dɪsˈɡaɪz/",pos:"idiom",def:"a good thing that seemed bad at first",ex:"Losing that job was a blessing in disguise.",syn:"hidden benefit"},
  {w:"to ring a bell",ipa:"/rɪŋ ə bel/",pos:"idiom",def:"to sound familiar",ex:"That name rings a bell.",syn:"sound familiar"},
 ]},
 {id:"academic",name:"Academic & Formal",icon:"🎓",lvl:"C1",words:[
  {w:"thrive",ipa:"/θraɪv/",pos:"verb",def:"to grow or do very well",ex:"Plants thrive in sunlight.",syn:"flourish, prosper"},
  {w:"undermine",ipa:"/ˌʌndəˈmaɪn/",pos:"verb",def:"to gradually weaken something",ex:"It undermined his authority.",syn:"weaken, sabotage"},
  {w:"alleviate",ipa:"/əˈliːvieɪt/",pos:"verb",def:"to make pain or problems less severe",ex:"This will alleviate stress.",syn:"ease, relieve"},
  {w:"exacerbate",ipa:"/ɪɡˈzæsəbeɪt/",pos:"verb",def:"to make a bad situation worse",ex:"It exacerbated the crisis.",syn:"worsen, aggravate"},
  {w:"advocate",ipa:"/ˈædvəkeɪt/",pos:"verb",def:"to publicly support an idea",ex:"He advocates reform.",syn:"support, champion"},
  {w:"comprise",ipa:"/kəmˈpraɪz/",pos:"verb",def:"to consist of; be made up of",ex:"The team comprises five people.",syn:"consist of, contain"},
  {w:"contemplate",ipa:"/ˈkɒntəmpleɪt/",pos:"verb",def:"to think about deeply",ex:"I'm contemplating a move.",syn:"consider, ponder"},
  {w:"deteriorate",ipa:"/dɪˈtɪəriəreɪt/",pos:"verb",def:"to become progressively worse",ex:"His health deteriorated.",syn:"worsen, decline"},
  {w:"facilitate",ipa:"/fəˈsɪlɪteɪt/",pos:"verb",def:"to make a process easier",ex:"Apps facilitate learning.",syn:"ease, enable"},
  {w:"mitigate",ipa:"/ˈmɪtɪɡeɪt/",pos:"verb",def:"to reduce the harm of something",ex:"Steps to mitigate risk.",syn:"lessen, reduce"},
  {w:"scrutinise",ipa:"/ˈskruːtɪnaɪz/",pos:"verb",def:"to examine very carefully",ex:"They scrutinised the data.",syn:"examine, inspect"},
  {w:"acknowledge",ipa:"/əkˈnɒlɪdʒ/",pos:"verb",def:"to accept or admit something is true",ex:"He acknowledged his mistake.",syn:"admit, recognise"},
  {w:"feasible",ipa:"/ˈfiːzəbl/",pos:"adj",def:"possible to do easily",ex:"Is that plan feasible?",syn:"viable, doable"},
  {w:"inherent",ipa:"/ɪnˈhɪərənt/",pos:"adj",def:"existing as a natural part of something",ex:"Risk is inherent in business.",syn:"intrinsic, built-in"},
  {w:"prevalent",ipa:"/ˈprevələnt/",pos:"adj",def:"widespread; common",ex:"The view is prevalent.",syn:"widespread, common"},
  {w:"nuance",ipa:"/ˈnjuːɑːns/",pos:"noun",def:"a subtle difference in meaning",ex:"The nuances of the language.",syn:"subtlety, shade"},
  {w:"consensus",ipa:"/kənˈsensəs/",pos:"noun",def:"general agreement",ex:"We reached a consensus.",syn:"agreement"},
  {w:"insight",ipa:"/ˈɪnsaɪt/",pos:"noun",def:"a deep, clear understanding",ex:"Valuable insight.",syn:"understanding, perception"},
 ]},
 {id:"business",name:"Business & Money",icon:"💼",lvl:"C1",words:[
  {w:"lucrative",ipa:"/ˈluːkrətɪv/",pos:"adj",def:"making a lot of money",ex:"A lucrative deal.",syn:"profitable"},
  {w:"viable",ipa:"/ˈvaɪəbl/",pos:"adj",def:"capable of working successfully",ex:"A viable business model.",syn:"workable, feasible"},
  {w:"incentive",ipa:"/ɪnˈsentɪv/",pos:"noun",def:"something that motivates you",ex:"A financial incentive.",syn:"motivation, spur"},
  {w:"revenue",ipa:"/ˈrevənjuː/",pos:"noun",def:"the money a business earns",ex:"Revenue grew by 10%.",syn:"income, earnings"},
  {w:"stakeholder",ipa:"/ˈsteɪkhəʊldə/",pos:"noun",def:"a person with an interest in a business",ex:"We consulted all stakeholders.",syn:"party, investor"},
  {w:"overheads",ipa:"/ˈəʊvəhedz/",pos:"noun",def:"ongoing running costs of a business",ex:"We cut our overheads.",syn:"running costs"},
  {w:"niche",ipa:"/niːʃ/",pos:"noun",def:"a specialised market segment",ex:"They found a profitable niche.",syn:"segment, specialty"},
  {w:"cutting-edge",ipa:"/ˈkʌtɪŋ edʒ/",pos:"adj",def:"the most advanced; newest",ex:"Cutting-edge technology.",syn:"state-of-the-art"},
  {w:"obsolete",ipa:"/ˈɒbsəliːt/",pos:"adj",def:"out of date; no longer used",ex:"The tech is obsolete.",syn:"outdated"},
  {w:"abundant",ipa:"/əˈbʌndənt/",pos:"adj",def:"existing in large quantities",ex:"Abundant resources.",syn:"plentiful, ample"},
  {w:"scarce",ipa:"/skeəs/",pos:"adj",def:"not enough; in short supply",ex:"Water is scarce here.",syn:"rare, limited"},
  {w:"lay off",ipa:"/leɪ ɒf/",pos:"phrase",def:"to dismiss workers (for economic reasons)",ex:"The firm laid off staff.",syn:"make redundant"},
  {w:"break even",ipa:"/breɪk ˈiːvn/",pos:"phrase",def:"to earn exactly what you spend",ex:"We broke even this year.",syn:"cover costs"},
  {w:"bargain",ipa:"/ˈbɑːɡɪn/",pos:"noun",def:"something bought cheaply; a good deal",ex:"It was a real bargain.",syn:"deal, steal"},
 ]},
 {id:"trends",name:"Trends & Change",icon:"📈",lvl:"C1",words:[
  {w:"plummet",ipa:"/ˈplʌmɪt/",pos:"verb",def:"to fall steeply and fast",ex:"Sales plummeted.",syn:"plunge, drop"},
  {w:"soar",ipa:"/sɔː/",pos:"verb",def:"to rise high and fast",ex:"Prices soared.",syn:"rocket, surge"},
  {w:"surge",ipa:"/sɜːdʒ/",pos:"verb",def:"to increase suddenly and strongly",ex:"Demand surged overnight.",syn:"jump, spike"},
  {w:"dwindle",ipa:"/ˈdwɪndl/",pos:"verb",def:"to gradually become smaller",ex:"Savings dwindled away.",syn:"shrink, diminish"},
  {w:"fluctuate",ipa:"/ˈflʌktʃueɪt/",pos:"verb",def:"to rise and fall irregularly",ex:"Prices fluctuate daily.",syn:"vary, swing"},
  {w:"peak",ipa:"/piːk/",pos:"verb",def:"to reach the highest point",ex:"Sales peaked in July.",syn:"top out, climax"},
  {w:"steady",ipa:"/ˈstedi/",pos:"adj",def:"developing gradually and evenly",ex:"A steady rise in profits.",syn:"stable, consistent"},
  {w:"gradual",ipa:"/ˈɡrædʒuəl/",pos:"adj",def:"happening slowly over time",ex:"A gradual improvement.",syn:"slow, progressive"},
  {w:"sharp",ipa:"/ʃɑːp/",pos:"adj",def:"sudden and large (of a change)",ex:"A sharp decline.",syn:"steep, sudden"},
  {w:"inevitable",ipa:"/ɪnˈevɪtəbl/",pos:"adj",def:"certain to happen, unavoidable",ex:"Change is inevitable.",syn:"unavoidable, certain"},
  {w:"detrimental",ipa:"/ˌdetrɪˈmentl/",pos:"adj",def:"causing harm",ex:"Detrimental to health.",syn:"harmful, damaging"},
  {w:"breakthrough",ipa:"/ˈbreɪkθruː/",pos:"noun",def:"an important discovery or advance",ex:"A medical breakthrough.",syn:"advance, leap"},
  {w:"setback",ipa:"/ˈsetbæk/",pos:"noun",def:"a problem that delays progress",ex:"A major setback.",syn:"hitch, obstacle"},
 ]},
 {id:"essay",name:"Essay & Argument",icon:"✍️",lvl:"C1",words:[
  {w:"furthermore",ipa:"/ˈfɜːðəmɔː/",pos:"adv",def:"in addition (formal linker)",ex:"Furthermore, costs would rise.",syn:"moreover, besides"},
  {w:"nevertheless",ipa:"/ˌnevəðəˈles/",pos:"adv",def:"despite that; however",ex:"It's risky; nevertheless, we'll try.",syn:"nonetheless, however"},
  {w:"consequently",ipa:"/ˈkɒnsɪkwəntli/",pos:"adv",def:"as a result",ex:"He lied; consequently, no one trusts him.",syn:"therefore, thus"},
  {w:"whereas",ipa:"/weərˈæz/",pos:"conj",def:"in contrast to; while",ex:"He likes tea, whereas I prefer coffee.",syn:"while, but"},
  {w:"albeit",ipa:"/ɔːlˈbiːɪt/",pos:"conj",def:"although; even though",ex:"A useful, albeit costly, plan.",syn:"although, though"},
  {w:"undoubtedly",ipa:"/ʌnˈdaʊtɪdli/",pos:"adv",def:"certainly; without doubt",ex:"This is undoubtedly true.",syn:"certainly, clearly"},
  {w:"arguably",ipa:"/ˈɑːɡjuəbli/",pos:"adv",def:"it can be argued that",ex:"It's arguably the best film.",syn:"possibly, conceivably"},
  {w:"dilemma",ipa:"/dɪˈlemə/",pos:"noun",def:"a hard choice between options",ex:"A moral dilemma.",syn:"quandary"},
  {w:"crucial",ipa:"/ˈkruːʃl/",pos:"adj",def:"extremely important",ex:"A crucial decision.",syn:"vital, essential"},
  {w:"compelling",ipa:"/kəmˈpelɪŋ/",pos:"adj",def:"strongly convincing",ex:"A compelling case.",syn:"convincing, persuasive"},
  {w:"counterargument",ipa:"/ˈkaʊntərˌɑːɡjumənt/",pos:"noun",def:"an opposing point of view",ex:"Consider the counterargument.",syn:"rebuttal, objection"},
  {w:"to some extent",ipa:"/tə sʌm ɪkˈstent/",pos:"phrase",def:"partly; in some degree",ex:"I agree to some extent.",syn:"partly, somewhat"},
  {w:"bear in mind",ipa:"/beər ɪn maɪnd/",pos:"phrase",def:"to remember/consider something",ex:"Bear in mind the cost.",syn:"keep in mind, note"},
 ]},
];
/* плоский банк для «слов дня» и поиска по клику */
const WORDBANK = DECKS.flatMap(d=>d.words.map(w=>({...w,cat:d.id,lvl:d.lvl})));

/* ===== Расширенная теория ===== */
Object.assign(BANK.theory, {
  "Conditionals":{title:"Conditionals (0–3 + mixed)",html:"<h3>The four types</h3><ul><li>Zero: <code>If you heat ice, it melts</code> (facts)</li><li>First: <code>If it rains, I'll stay</code> (real future)</li><li>Second: <code>If I won, I would travel</code> (unreal now)</li><li>Third: <code>If I had known, I would have come</code> (past regret)</li></ul><h3>Mixed</h3><p><code>If I had studied medicine, I would be a doctor now</code> (past condition → present result).</p>"},
  "Articles":{title:"Articles: a / an / the / zero",html:"<h3>Indefinite a/an</h3><p>First mention or one of many: <code>I saw a dog</code>.</p><h3>Definite the</h3><p>Specific/known, unique things: <code>the sun</code>, <code>the dog I saw</code>.</p><h3>Zero article</h3><p>General plurals & uncountables: <code>Cats are cute</code>, <code>Water is vital</code>. Note: <code>go to school</code> (no the) vs <code>go to the school</code> (the building).</p>"},
  "Modal verbs":{title:"Modals: ability, obligation, deduction",html:"<h3>Deduction</h3><ul><li><code>must be</code> (sure it's true)</li><li><code>can't be</code> (sure it's false)</li><li><code>might/could be</code> (possible)</li></ul><h3>Obligation</h3><p><code>must</code> (strong), <code>have to</code> (external), <code>should</code> (advice), <code>needn't</code> (not necessary).</p><h3>Past</h3><p><code>should have done</code> (regret), <code>must have done</code> (past deduction).</p>"},
  "Reported speech":{title:"Reported speech",html:"<h3>Backshift</h3><p>Present→past, will→would, can→could: <code>\"I am tired\" → He said he was tired</code>.</p><h3>Questions</h3><p>No inversion, use if/whether: <code>She asked if I was ready</code>.</p><h3>Commands</h3><p><code>tell/ask + to + verb</code>: <code>He told me to wait</code>.</p>"},
  "Passive voice":{title:"Passive voice",html:"<h3>Form</h3><p><code>be + past participle</code>. Focus on the action, not the doer: <code>The bridge was built in 1990</code>.</p><h3>Across tenses</h3><ul><li>Present: <code>is made</code></li><li>Past: <code>was made</code></li><li>Perfect: <code>has been made</code></li><li>Modal: <code>can be made</code></li></ul>"},
  "Phrasal verbs":{title:"Phrasal verbs",html:"<h3>Separable vs inseparable</h3><p>Separable: <code>turn it off</code> ✓ / <code>turn off it</code> ✗. Inseparable: <code>look after them</code> ✓.</p><h3>High-value set</h3><ul><li>come up with = invent</li><li>put up with = tolerate</li><li>get along with = have good relations</li><li>look forward to (+ V-ing) = anticipate happily</li></ul>"},
});
